config/routes.rb
Rails.application.routes.draw do
  resources :referrals

  resources :campaigns, only: [:index, :show, :update, :create]
  post 'campaigns/referral/:permalink' => 'campaigns#refer', as: 'campaign_referral'

  devise_for :merchant_users
  devise_for :users
  resources :users

  get 'countries/:id', to: 'countries#show', as: 'country'

  root to: "home#index"
  ActiveAdmin.routes(self)
end

app/models/referral.rb
class Referral < ActiveRecord::Base
  is_impressionable :counter_cache => true
  include Rails.application.routes.url_helpers

  has_many :subordinates, class_name: 'Referral', foreign_key: 'parent_id'
  belongs_to :parent, class_name: 'Referral', counter_cache: true
  include ActiveUUID::UUID
  include AASM
  after_initialize do
    self.uuid = SecureRandom.uuid if self.uuid.nil?
    if self.relative_url.nil?
      controller_path = eval("#{self.referable.class.name.downcase}_path(self.referable)")
      self.relative_url = controller_path.concat("?uuid=#{self.uuid}")
    end
  end

  belongs_to :user
  belongs_to :referable, polymorphic: true, counter_cache: true

  def referral_url
    File.join(root_url, self.relative_url)
  end

  aasm :column => :status do
    state :new, :initial => true
    state :pending
    state :accomplished
    state :cancelled

    event :pend do
      transitions :from => :new, :to => :pending
    end

    event :accomplish do
      transitions :from => :pending, :to => :accomplished
    end

    event :cancel do
      transitions :from => [:new, :pending], :to => :cancelled
    end
  end
end

app/controllers/referrals_controller.rb
class ReferralsController < ApplicationController
  before_action :set_referral, only: [:show, :edit, :update, :destroy]

  # GET /referrals
  # GET /referrals.json
  def index
    @referrals = Referral.all
  end

  # GET /referrals/1
  # GET /referrals/1.json
  def show
  end

  # GET /referrals/new
  def new
    @referral = Referral.new
  end

  # GET /referrals/1/edit
  def edit
  end

  # POST /referrals
  # POST /referrals.json
  def create
    @referral = Referral.new(referral_params)

    respond_to do |format|
      if @referral.save
        format.html { redirect_to @referral, notice: 'Referral was successfully created.' }
        format.json { render :show, status: :created, location: @referral }
      else
        format.html { render :new }
        format.json { render json: @referral.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /referrals/1
  # PATCH/PUT /referrals/1.json
  def update
    respond_to do |format|
      if @referral.update(referral_params)
        format.html { redirect_to @referral, notice: 'Referral was successfully updated.' }
        format.json { render :show, status: :ok, location: @referral }
      else
        format.html { render :edit }
        format.json { render json: @referral.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /referrals/1
  # DELETE /referrals/1.json
  def destroy
    @referral.destroy
    respond_to do |format|
      format.html { redirect_to referrals_url, notice: 'Referral was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_referral
    @referral = Referral.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def referral_params
    params[:referral]
  end
end

app/helpers/referrals_helper.rb
module ReferralsHelper
  def validate_referral_uuid(referral_uuid)
    Referral.find_by_uuid(referral_uuid) ? referral_uuid : nil
  end
end

app/views/referrals/_form.html.erb
<%= form_for(@referral) do |f| %>
    <% if @referral.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@referral.errors.count, "error") %> prohibited this referral from being saved:</h2>

          <ul>
            <% @referral.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/referrals/edit.html.erb
<h1>Editing Referral</h1>

<%= render 'form' %>

<%= link_to 'Show', @referral %> |
<%= link_to 'Back', referrals_path %>

app/views/referrals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Referrals</h1>

<table>
  <thead>
  <tr>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @referrals.each do |referral| %>
      <tr>
        <td><%= link_to 'Show', referral %></td>
        <td><%= link_to 'Edit', edit_referral_path(referral) %></td>
        <td><%= link_to 'Destroy', referral, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Referral', new_referral_path %>

app/views/referrals/new.html.erb
<h1>New Referral</h1>

<%= render 'form' %>

<%= link_to 'Back', referrals_path %>

app/views/referrals/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_referral_path(@referral) %> |
<%= link_to 'Back', referrals_path %>