config/routes.rb
Rails.application.routes.draw do
  resources :referrals

  resources :campaigns, only: [:index, :show, :update, :create]
  post 'campaigns/referral/:permalink' => 'campaigns#refer', as: 'campaign_referral'

  devise_for :merchant_users
  devise_for :users
  resources :users

  get 'countries/:id', to: 'countries#show', as: 'country'

  root to: "home#index"
  ActiveAdmin.routes(self)
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  is_impressionable :counter_cache => true
  include ActiveUUID::UUID
  after_initialize { self.uuid = SecureRandom.uuid if self.uuid.nil? }

  attr_accessor :referral_uuid

  belongs_to :merchant_user, dependent: :destroy
  has_many :campaign_pledges
  has_many :referrals, as: :referable
  has_many :addresses, as: :addressable
  has_one :master_pledge, -> { where is_master: true },
          inverse_of: :campaign,
          class_name: 'CampaignPledge',
          foreign_key: :campaign_id

  scope :active, -> { where(status: 'launched') }

  cattr_accessor :search_scopes do
    []
  end

  has_many :images

  has_one :master_image, -> { where is_master: true },
          inverse_of: :campaign,
          class_name: 'Image',
          foreign_key: :campaign_id

  accepts_nested_attributes_for :campaign_pledges, :allow_destroy => true #, :reject_if => lambda { |a| a[:content].blank?}
  accepts_nested_attributes_for :images, :allow_destroy => true #, :reject_if => lambda { |a| a[:content].blank?}

  def self.add_search_scope(name, &block)
    self.singleton_class.send(:define_method, name.to_sym, &block)
    search_scopes << name.to_sym
  end

  def self.like_any(fields, values)
    where fields.map { |field|
            values.map { |value|
              arel_table[field].matches("%#{value}%")
            }.inject(:or)
          }.inject(:or)
  end

  add_search_scope :in_taxon do |taxon|
    includes(:classifications).
        where("campaigns_taxons.taxon_id" => taxon.self_and_descendants.pluck(:id)).
        order("campaigns_taxons.position ASC")
  end

  def lowest_award
    self.campaign_pledges.map(&:unit_budge).min rescue nil
  end

  def find_referral_by_user(user)
    return nil if user.nil?
    self.referrals.where(:user_id => user.id).first
  end

  def is_referral_valid?(referral)
    return false if referral.nil?
    referral.referable_id == self.id && referral.referable_type == self.class.name
  end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :set_campaign, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:refer]

  # GET /campaigns
  # GET /campaigns.json
  def index
    @campaigns = Campaign.all
  end

  # GET /campaigns/1
  # GET /campaigns/1.json
  def show
    @referral = @campaign.find_referral_by_user(current_user)
    @campaign.referral_uuid = params[:uuid]
    # save referral uuid in the field of messages in impressions
    impressionist(@campaign, params[:uuid])
  end

  def refer
    @campaign = Campaign.find_by_permalink(params[:permalink])
    referral = Referral.find_by_uuid(params[:referral_uuid])
    parent_id =
        if @campaign.is_referral_valid?(referral)
          referral.parent_id
        else
          nil
        end
    @campaign.referrals.create(:user_id => current_user.id, :parent_id => parent_id)
    redirect_to campaign_path(@campaign)
  end

  # GET /campaigns/new
  def new
    @campaign = Campaign.new
  end

  # GET /campaigns/1/edit
  def edit
  end

  # POST /campaigns
  # POST /campaigns.json
  def create
    @campaign = Campaign.new(campaign_params)

    respond_to do |format|
      if @campaign.save
        format.html { redirect_to @campaign, notice: 'Campaign was successfully created.' }
        format.json { render :show, status: :created, location: @campaign }
      else
        format.html { render :new }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campaigns/1
  # PATCH/PUT /campaigns/1.json
  def update
    respond_to do |format|
      if @campaign.update(campaign_params)
        format.html { redirect_to merchant_campaign_path(@campaign), notice: 'Campaign was successfully updated.' }
        format.json { render :show, status: :ok, location: @campaign }
      else
        format.html { render :edit }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaigns/1
  # DELETE /campaigns/1.json
  def destroy
    @campaign.destroy
    respond_to do |format|
      format.html { redirect_to campaigns_url, notice: 'Campaign was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_campaign
    @campaign = Campaign.includes(:campaign_pledges).find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def campaign_params
    params.require(:campaign).permit(:id, :title, :description, :start_at, :expired_at, :permalink, :campaign_pledges_attributes => [:id, :title, :description, :total_budget, :unit_budget], :images_attributes => [:id, :image])
  end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
  def cache_key_for_campaigns
    count = @campaigns.count
    max_updated_at = (@campaigns.maximum(:updated_at) || Date.today).to_s(:number)
    "#{current_locale}campaigns/all-#{params[:page]}-#{max_updated_at}-#{count}"
  end
end

app/views/campaigns/_form.html.erb
<%= javascript_include_tag 'merchant_fields.js' %>
<div class="col-md-8">
  <%= form_for(@campaign) do |f| %>
      <% if @campaign.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@campaign.errors.count, "error") %> prohibited this campaign from being saved:</h2>

            <ul>
              <% @campaign.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="actions">
        <%= hidden_field(:campaign, :merchant_user_id) %>
        <%= f.hidden_field :id %>
        Title: <%= f.text_field :title %><br/>
        Description : <%= f.text_area :description %><br/>
        Permalink : <%= f.text_field :permalink %><br/>
        start_at : <%= f.datetime_select :start_at %><br/>
        expired_at : <%= f.datetime_select :expired_at %><br/>
        <hr>
        <%= f.fields_for :images, :html => {:multipart => true} do |builder| %>
            <%= render 'images/form', :f => builder %>
        <% end %>
        <div>
          <%= link_to_add_fields "Add Image", f, :images %>
        </div>
        <%= f.fields_for :campaign_pledges do |builder| %>
            <%= render 'campaign_pledges/form', :f => builder %>
        <% end %>
        <div><%= link_to_add_fields "Add Pledge", f, :campaign_pledges %></div>
        <%= f.submit %>
      </div>
  <% end %>
</div>

app/views/campaigns/show.html.erb
<div class="row" id="myCampaign">
  <div class="col-md-8">
    <%= render :partial => 'shared/campaign', :locals => {:campaign => @campaign} %>
  </div>
  <div class="col-md-12">
    <% if @referral %>
        <a href="#myModal" role="button" class="btn btn-warning" data-toggle="modal">
          <span class="glyphicon glyphicon-hand-up"></span>
          <%= I18n.t :share %>
          <i class="fa fa-weixin"></i>
        </a>

        <a href="#myModal" role="button" class="btn btn-warning" data-toggle="modal">
          <span class="glyphicon glyphicon-hand-up"></span>
          <%= I18n.t :share %>
          <i class="fa fa-weibo"></i>
        </a>

        <a href="#myModal" role="button" class="btn btn-warning" data-toggle="modal">
          <span class="glyphicon glyphicon-hand-up"></span>
          <%= I18n.t :share %>
          <i class="fa fa-facebook"></i>
        </a>

        <a href="#myModal" role="button" class="btn btn-warning" data-toggle="modal">
          <span class="glyphicon glyphicon-hand-up"></span>
          <%= I18n.t :share %>
          <i class="fa fa-twitter"></i>
        </a>
        <%= social_share_button_tag(@referral.referral_url) %>
        <pre>
            <%= @referral.referral_url %>
          </pre>
    <% else %>
        <%= form_for :referral, url: campaign_referral_path(@campaign.permalink), :html => {:id => 'referral_form'} do |f| %>
            <%= hidden_field(:campaign, :referral_uuid) %>
            <%= link_to 'javascript:{}', onclick: "document.getElementById('referral_form').submit();", role: 'button', class: 'btn btn-warning btn-lg' do %>
                <span class="glyphicon glyphicon-hand-up"></span>
                <%= I18n.t :willing_to_share %>
            <% end %>
        <% end %>
    <% end %>
  </div>
</div>